### ISSUE TITLE
Adding more timestamps

### ISSUE THREAD

**Issue by DooorisXu** [MLavrentyev/TeamManager#29] opened 2019-01-06 00:12 UTC
Stamping the time the request is approved, the time the order is placed, and the time the product is delivered -- the time when the button is clicked on.  Time zone = eastern time.

**Comment by MLavrentyev** [comment] 2019-01-08 20:37
This is being worked on at the same time as #28 - (for each of approval, ordering, delivery, it will have a timestamp and person attached)

For example:
Purchase Request by person-0
- approved on 1/8/2019 by person-1
- ordered on 1/9/2019 by person-2
- delivered on 1/10/2019 (signed off by person-3)

**Comment by MLavrentyev** [comment] 2019-01-08 23:38
Duplicate of #28

**Closed** 2019-01-08 23:38 UTC
